site_name: Open edX on OpenStack
theme: readthedocs
markdown_extensions:
  - admonition
  - codehilite
  - markdown_include.include
  - linkify
pages:
  - Home: index.md
  - Prerequisites: prerequisites.md
  - Deployment Options: deployment_options.md
  - Analytics: analytics.md